# -------------------------------------------------- #
#               DamageIndicators Config              #
# -------------------------------------------------- #

# Master switch for the plugin.
# If set to false, no indicators will be shown.
# You can also change this setting with the `/di toggle` command.
enabled: true

# Text to appear at the beginning of the damage indicator.
# You can use color codes with '&' (default: '&c♥ ')
indicator-prefix: '&c♥ '

# Time the damage indicator stays on screen (default: 1.5)
indicator-duration-seconds: 1.5

# World Blacklist
# List the names of the worlds where you want to disable damage indicators.
disabled-worlds:
# - "world_lobby"
# - "creative"